### ISSUE TITLE
Incompatible with 64 bit systems

### ISSUE THREAD

**Issue by pljluca** [harturo123/QlikSenseReloader#2]
Hi, 
when I execute **QlikSenseReloader.exe** on my Windows 7 64 bit the systems say me that the application is incompatible to run on 64 bit systems.

How can I solve this?

Thanks a lot
Luca

**Comment by harturo123** [comment]
Hi Luca,

It do works on my Windows 10 64-bit machine, so it might be an issue related to the Windows version instead. If you have Python installed, you can download and run [QlikSenseReloader.py](https://github.com/harturo123/QlikSenseReloader/blob/master/QlikSenseReloader.py) directly.

Arturo

**Comment by pljluca** [comment]
Hi Arturo,
I use Windows 7.
How have you compile QlikSenseReloader.exe?

Thanks a lot
Luca

**Comment by harturo123** [comment]
I used [pyInstaller](https://www.pyinstaller.org/).
